"""
Convertly V2 — Enterprise Table Extraction Data Models
Represents structural, topological, confidence, intelligence, routing,
and validation entities across the document processing lifecycle.
"""

from dataclasses import dataclass, field
from typing import List, Optional, Any, Tuple, Dict
import time

from .constants import (
    DocumentType,
    TableTopology,
    DocumentGenre,
    EngineType,
    CONFIDENCE_HIGH,
    QUALITY_FALLBACK_THRESHOLD,
)


@dataclass
class BoundingBox:
    """Represents a standard 2D axis-aligned bounding box (x0, y0, x1, y1)."""
    x0: float
    y0: float
    x1: float
    y1: float

    @property
    def width(self) -> float:
        return max(0.0, self.x1 - self.x0)

    @property
    def height(self) -> float:
        return max(0.0, self.y1 - self.y0)

    @property
    def area(self) -> float:
        return self.width * self.height

    def to_tuple(self) -> Tuple[float, float, float, float]:
        return (self.x0, self.y0, self.x1, self.y1)

    @classmethod
    def from_tuple(cls, coords: Tuple[float, float, float, float]) -> "BoundingBox":
        return cls(x0=coords[0], y0=coords[1], x1=coords[2], y1=coords[3])


@dataclass
class TableCell:
    """Represents an individual cell in an extracted table grid."""
    text: str
    bbox: Tuple[float, float, float, float]  # (x0, y0, x1, y1)
    row_idx: int
    col_idx: int
    rowspan: int = 1
    colspan: int = 1
    is_header: bool = False
    indent_level: int = 0
    data_type: str = "text"  # 'text' | 'number' | 'currency' | 'percentage' | 'date'
    typed_value: Any = None
    format_code: Optional[str] = None
    confidence: float = 1.0

    @property
    def width(self) -> float:
        return max(0.0, self.bbox[2] - self.bbox[0])

    @property
    def height(self) -> float:
        return max(0.0, self.bbox[3] - self.bbox[1])


@dataclass
class TableRow:
    """Represents a row of cells with bounding box and header flag."""
    cells: List[TableCell] = field(default_factory=list)
    row_idx: int = 0
    bbox: Tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)
    is_header: bool = False


@dataclass
class TableBlock:
    """Represents a structured table block on a document page."""
    bbox: Tuple[float, float, float, float]  # (x0, y0, x1, y1)
    rows: List[TableRow] = field(default_factory=list)
    table_type: str = "lattice"  # 'lattice' | 'stream' | 'key_value' | 'summary'
    has_merged_cells: bool = False
    page_idx: int = 0
    engine: str = "unknown"
    confidence: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def row_count(self) -> int:
        return len(self.rows)

    @property
    def col_count(self) -> int:
        if not self.rows:
            return 0
        return max(len(r.cells) for r in self.rows)


@dataclass
class KeyValueBlock:
    """Represents key-value metadata pairs (e.g. Invoice #, Bill-To, Date)."""
    items: List[Tuple[str, str]] = field(default_factory=list)
    bbox: Tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)
    section: str = "header"  # 'header' | 'footer' | 'notes'


@dataclass
class PageLayout:
    """Represents the complete semantic decomposition of a single document page."""
    page_idx: int
    width: float
    height: float
    is_scanned: bool = False
    tables: List[TableBlock] = field(default_factory=list)
    key_values: List[KeyValueBlock] = field(default_factory=list)
    text_lines: List[Tuple[str, Tuple[float, float, float, float]]] = field(default_factory=list)


@dataclass
class ConfidenceScore:
    """Multi-vector confidence evaluation for an extracted table block."""
    overall: float = 1.0
    column_alignment: float = 1.0
    row_continuity: float = 1.0
    type_consistency: float = 1.0
    header_validity: float = 1.0
    density_score: float = 1.0
    details: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_high_confidence(self) -> bool:
        return self.overall >= CONFIDENCE_HIGH


@dataclass
class QualityScore:
    """Arbiter quality assessment quantifying structural soundness and defects."""
    score: float = 1.0
    is_acceptable: bool = True
    passed_checks: List[str] = field(default_factory=list)
    violations: List[str] = field(default_factory=list)
    penalties: Dict[str, float] = field(default_factory=dict)

    @property
    def meets_fallback_threshold(self) -> bool:
        return self.score >= QUALITY_FALLBACK_THRESHOLD


@dataclass
class EngineMetrics:
    """Telemetry captured during a single extraction or processing stage."""
    engine_name: str
    page_idx: int = 0
    execution_time_ms: float = 0.0
    memory_delta_mb: float = 0.0
    cell_count: int = 0
    table_count: int = 0
    confidence: float = 1.0
    warnings: List[str] = field(default_factory=list)


@dataclass
class ExtractionCandidate:
    """Candidate output generated by an extraction engine awaiting arbitration."""
    engine_type: str
    tables: List[TableBlock] = field(default_factory=list)
    confidence: ConfidenceScore = field(default_factory=ConfidenceScore)
    quality: QualityScore = field(default_factory=QualityScore)
    metrics: EngineMetrics = field(default_factory=lambda: EngineMetrics(engine_name="unknown"))
    warnings: List[str] = field(default_factory=list)


@dataclass
class DocumentProfile:
    """Comprehensive document intelligence profile produced prior to extraction."""
    total_pages: int
    doc_type: str = DocumentType.NATIVE_TEXT.value
    genre: str = DocumentGenre.GENERIC_TABLE.value
    page_profiles: List[Dict[str, Any]] = field(default_factory=list)
    has_scanned_pages: bool = False
    has_mixed_layouts: bool = False
    has_ruling_lines: bool = False
    avg_char_density: float = 0.0
    dominant_font_sizes: List[float] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RoutingDecision:
    """Optimal extraction route and fallback strategy determined by Document Intelligence."""
    primary_engine: str = EngineType.LATTICE.value
    fallback_engine: Optional[str] = EngineType.STREAM.value
    reason: str = "Standard grid lines detected."
    estimated_complexity: str = "low"  # 'low' | 'medium' | 'high'
    ocr_required: bool = False
    streaming_mode: bool = False
    page_routes: Dict[int, str] = field(default_factory=dict)


@dataclass
class ValidationReport:
    """Audit report generated after structural and mathematical reconciliation."""
    is_valid: bool = True
    math_checks_passed: int = 0
    math_checks_failed: int = 0
    empty_rows_stripped: int = 0
    split_words_repaired: int = 0
    repaired_cells_count: int = 0
    violations: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class ExtractionResult:
    """Final unified output from the table extraction and reconstruction pipeline."""
    tables: List[TableBlock] = field(default_factory=list)
    page_layouts: List[PageLayout] = field(default_factory=list)
    document_profile: Optional[DocumentProfile] = None
    routing_decision: Optional[RoutingDecision] = None
    validation_report: Optional[ValidationReport] = None
    quality_scores: List[QualityScore] = field(default_factory=list)
    metrics: List[EngineMetrics] = field(default_factory=list)
    excel_bytes: Optional[bytes] = None
    execution_time_ms: float = 0.0
    warnings: List[str] = field(default_factory=list)
